name: appfluttersecurity_
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # Adicionando as dependências necessárias para o aplicativo de segurança
  camera: ^0.10.5+5
  http: ^1.1.0
  path_provider: ^2.1.1
  path: ^1.8.3
  permission_handler: ^11.0.1
  proximity_sensor: ^1.0.4
  flutter_local_notifications: ^16.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true